name: "Math++ Tests"

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '18 13 * * 6'

jobs:
  analyze:
    name: Math++ Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'cpp' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
        
    - run: |
       g++ testing_software/testing_software.cpp -O3 -o testing_software.out
       chmod +x testing_software.out
       ./testing_software.out